{
    # lm settings
    tokenizer_name: "facebook/galactica-6.7b",
    lm_name: "facebook/galactica-6.7b",
    seq_len: 256,

    # image encoder settings
    encoder_name: 'clip_resnet',
    freeze_img_encoder: false,
    pretrained_img_encoder: true,
    adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 4, "ff_attr": "fc2"}, "attention": {"adapter_type": "normal", "downsample_factor": 4, "attn_attr": "self_attn"}},
    ask_string: 'Describe the figure:',

    # train settings 
    batch_size: 8,
    train_steps: 12500,
    lr: 8.0e-7,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 2.0e-7,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1, 
    image_size: 384,
    
    gradient_accumulation_steps: 8,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'scicap',
    train_dataset_dir: 'dataset/scicap/train',
    eval_dataset_name: 'scicap',
    eval_dataset_dir: 'dataset/scicap/val',
    cache_prefix: 'facebook_resnet',
    
    save: "checkpoints/multimodal_facebook_resnet",
    load: "checkpoints/multimodal_facebook_resnet",
    #save_every: 500,

    eval_every: 2500,
    name: duan,
    entity: insightsnet,
}